### ISSUE TITLE
Not working with 2022 Beta3

### ISSUE THREAD

**Issue by ngreen-gt** [Oblarg/Oblog#15]
Added everything into build.gradle from prior project Oblog 3.1.2 after updating to the beta3 wpilib project.  Did not resolve the Oblog classes (logger, config, etc).  So showed as a problem.  Was able to build robot code with highlighted Oblog problems, but produced errors when deploying on robot.  Will try to get more info on them.

`1 not available, check if controller is plugged in
CS: USB Camera 0: Connecting to USB camera on /dev/video0
Unhandled exception: java.lang.ClassNotFoundException: edu.wpi.first.wpilibj.Sendable
Error at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source): Unhandled exception: java.lang.ClassNotFoundException: edu.wpi.first.wpilibj.Sendable
The robot program quit unexpectedly. This is usually due to a code error.
The above stacktrace can help determine where the error occurred.
See https://wpilib.org/stacktrace for more information.
at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
The startCompetition() method (or methods called by it) should have handled the exception above.
at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
at frc.robot.Robot.robotInit(Robot.java:36)
at edu.wpi.first.wpilibj.TimedRobot.startCompetition(TimedRobot.java:107)
at edu.wpi.first.wpilibj.RobotBase.runRobot(RobotBase.java:373)
at edu.wpi.first.wpilibj.RobotBase.startRobot(RobotBase.java:463)
at frc.robot.Main.main(Main.java:27)
Warning at edu.wpi.first.wpilibj.RobotBase.runRobot(RobotBase.java:388): The robot program quit unexpectedly. This is usually due to a code error.`

I did remove Oblog and was able to successfully deploy robot code, so I think the problem is within it.

**Comment by Oblarg** [comment]
Check the new release:

https://github.com/Oblarg/Oblog/releases/tag/4.0.0

**Comment by ngreen-gt** [comment]
It is still having issues locating 4.0.8.  

With the dependency of `com.github.Oblarg.Oblog:4.0.8` it results in:
```
FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\User\Documents\Robot2022\build.gradle' line: 89

* What went wrong:
Could not determine the dependencies of task ':jar'.
> Could not resolve all files for configuration ':runtimeClasspath'.
   > Could not find com.github.Oblarg.Oblog:4.0.8:.
     Required by:
         project :
```
And adding the `:lib:`  it results in:

```
FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\User\Documents\Robot2022\build.gradle' line: 89

* What went wrong:
Could not determine the dependencies of task ':jar'.
> Could not resolve all files for configuration ':runtimeClasspath'.
   > Could not resolve com.github.Oblarg.Oblog:lib:4.0.8.
     Required by:
         project :
      > Could not resolve com.github.Oblarg.Oblog:lib:4.0.8.
         > Could not get resource 'https://frcmaven.wpi.edu/ui/native/vendor-mvn-release/com/github/Oblarg/Oblog/lib/4.0.8/lib-4.0.8.pom'.
            > Could not HEAD 'https://frcmaven.wpi.edu/ui/native/vendor-mvn-release/com/github/Oblarg/Oblog/lib/4.0.8/lib-4.0.8.pom'. Received status code 403 from server: Forbidden
```

**Comment by Oblarg** [comment]
Okay, jitpack multi-module support is gone for gradle 7, it seems.  Remove `lib` from the dependency path, and boost the version to 4.0.9.
